### ISSUE TITLE
Cannot mock readonly class

### ISSUE THREAD

**Issue by Gyalomalom** [mockery/mockery#1317]
### Mockery Version

1.5.1

### PHP Version

PHP 8.2

### Issue Description

After upgrading to PHP 8.2 and making a number of classes readonly, our tests began failing. We use a lot of dependency injection so in those cases we need to mock the injected classes. I get the following error:

```
In EvalLoader.php(34) : eval()'d code line 30:
                                                                                                                                                                               
Non-readonly class Mockery_7_ClassToBeMocked cannot extend readonly class ClassToBeMocked
```

If I remove readonly from the class and instead make the properties readonly, it works, so currently we are using this approach as a workaround, but I would like to know if Mockery is planning to add support to readonly classes in the future.

### Steps to Reproduce

Create a mock of a readonly class using Mockery.

### Expected Behavior

The mock is successfully created.

### Actual Behavior

An exception is thrown.

### Exception or Error

```
In EvalLoader.php(34) : eval()'d code line 30:
                                                                                                                                                                               
Non-readonly class Mockery_7_ClassToBeMocked cannot extend readonly class ClassToBeMocked
```

**Comment by ghostwriter** [comment]
Hey @Gyalomalom,

Thanks for reporting this issue.

I wanted to give some updates, but I don't have the full resolution yet.

Working on a fix for this in #1319 but it is not that simple (and may not be possible because of `readonly` class restrictions) so I need a little more time to address this issue.

I really appreciate your patience as we work through this issue together, thank you.

**Comment by Gyalomalom** [comment]
Thank you for the update, I will keep an eye on this issue.

**Comment by neoighodaro** [comment]
Hey... any update here?

**Comment by kyryl-bogach** [comment]
Seems to be a PHPUnit limitation:

![image](https://github.com/user-attachments/assets/ad0573d4-fb2b-4ca4-aae6-032870256d9c)

https://docs.phpunit.de/en/10.5/test-doubles.html

**Comment by tomasbreffitt** [comment]
> Seems to be a PHPUnit limitation:
> 
> ![image](https://private-user-images.githubusercontent.com/24867662/348239001-ad0573d4-fb2b-4ca4-aae6-032870256d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYzMDIsIm5iZiI6MTcyODQyNjAwMiwicGF0aCI6Ii8yNDg2NzY2Mi8zNDgyMzkwMDEtYWQwNTczZDQtZmIyYi00Y2E0LWFhZTYtMDMyODcwMjU2ZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OTVlMzc5ZjZiNzY5N2Q4Yjg5OGJkYzFjYTIwN2ZjYWI1ZDVjZTU3MjRlYzIxYjRjMTE1NGM4Nzg5ZmMyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XYPiejrwSDbLBO4dp-Xsvb0Zy0ECn5zmtLiLXBZlNlk)
> 
> https://docs.phpunit.de/en/10.5/test-doubles.html

This has been resolved for PHPUnit in 11.2.0 https://github.com/sebastianbergmann/phpunit/blob/11.2.0/ChangeLog-11.2.md

It also is no longer in the documentation https://docs.phpunit.de/en/11.4/test-doubles.html#test-doubles

**Comment by smilesrg** [comment]
Bug still exists

**Comment by widoz** [comment]
The bug still exists because the PR mentioned above was closed without being merged. Latest comment by the developer was 

> Using clone on test doubles for classes that are declared readonly works on PHP >= 8.3.

So I assume that, if you want to double `readonly` classes you can update to PHP 8.3 or temporarly remove the `readonly` modifier from the class, applying it per properties.

**Comment by st0at** [comment]
PHP 8.4.8
mockery/mockery: 1.6.12

Fatal error: Non-readonly class Mockery_... cannot extend readonly class ...
